name: Daily Quote Updater

on:
  schedule:
    - cron: "0 5 * * *"  # Runs every day at 5:00 UTC (adjust if needed)
  workflow_dispatch:     # Allows you to manually run the workflow

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run quote updater
        run: python scripts/update_quote.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "✨ Update daily motivational quote"
          git push
